import type { INodeProperties } from 'n8n-workflow';

export const commonCredentialProperties: INodeProperties[] = [
	{
		displayName: 'Host',
		name: 'host',
		type: 'string',
		default: '',
		placeholder: 'https://my-sap-system.example.com',
		description: 'SAP origin only, without a service path, query string, or credentials',
		required: true,
	},
	{
		displayName: 'SAP Client',
		name: 'sapClient',
		type: 'string',
		default: '',
		placeholder: '100',
		description: 'Optional three-digit SAP client sent as sap-client',
	},
	{
		displayName: 'SAP Language',
		name: 'sapLanguage',
		type: 'string',
		default: '',
		placeholder: 'EN',
		description: 'Optional two-letter SAP language sent as sap-language',
	},
	{
		displayName: 'Service Policies JSON',
		name: 'servicePoliciesJson',
		type: 'string',
		typeOptions: { rows: 14 },
		default: '',
		placeholder:
			'{"/sap/opu/odata/sap/API_BUSINESS_PARTNER":{"version":"v2","allowMetadata":false,"entities":{"A_BusinessPartner":{"operations":["getMany"],"fields":["BusinessPartner"],"keyFields":{},"filterFields":{"BusinessPartner":"string"},"orderByFields":["BusinessPartner"]}}}}',
		description:
			'Deny-by-default allowlist for service paths, protocol versions, entity sets, read/write operations, fields, keys, filters, sorting, and concurrency rules',
		required: true,
	},
	{
		displayName: 'Allow SAP Service Catalog Discovery',
		name: 'allowServiceDiscovery',
		type: 'boolean',
		default: false,
		description:
			'Whether this credential may list the OData V2 services visible to the SAP user through Gateway CATALOGSERVICE. Discovery does not grant execution access; Service Policies JSON remains authoritative.',
	},
	{
		displayName: 'Maximum Catalog Services',
		name: 'maxCatalogServices',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 1000 },
		default: 250,
		description: 'Maximum number of services returned by one catalog discovery request',
		displayOptions: { show: { allowServiceDiscovery: [true] } },
	},
	{
		displayName: 'Allow Private Network Access',
		name: 'allowPrivateNetwork',
		type: 'boolean',
		default: false,
		description:
			'Whether literal private IPs and localhost may be used. DNS resolution and network egress controls must still be enforced outside the node.',
	},
	{
		displayName: 'Allow Plain HTTP',
		name: 'allowInsecureHttp',
		type: 'boolean',
		default: false,
		description: 'Whether HTTP may be used for isolated local tests. Keep disabled in real environments.',
	},
	{
		displayName: 'Validate TLS Certificate',
		name: 'rejectUnauthorized',
		type: 'boolean',
		default: true,
		description: 'Whether invalid or untrusted server certificates must be rejected',
	},
	{
		displayName: 'Maximum Rows',
		name: 'maxRows',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 10000 },
		default: 1000,
		description: 'Credential-level maximum returned rows per item',
	},
	{
		displayName: 'Maximum Pages',
		name: 'maxPages',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 100 },
		default: 10,
		description: 'Maximum number of server-driven pagination requests per item',
	},
	{
		displayName: 'Maximum URL Length',
		name: 'maxUrlLength',
		type: 'number',
		typeOptions: { minValue: 512, maxValue: 32768 },
		default: 8192,
		description: 'Maximum generated or server-provided URL length',
	},
	{
		displayName: 'Maximum Response Size (Bytes)',
		name: 'maxResponseBytes',
		type: 'number',
		typeOptions: { minValue: 1024, maxValue: 10485760 },
		default: 1048576,
		description: 'Cumulative serialized response limit per item',
	},
	{
		displayName: 'Maximum Write Request Size (Bytes)',
		name: 'maxRequestBytes',
		type: 'number',
		typeOptions: { minValue: 128, maxValue: 10485760 },
		default: 1048576,
		description: 'Maximum serialized OData create or update body per input item',
	},
	{
		displayName: 'Maximum Writes Per Execution',
		name: 'maxWrites',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 1000 },
		default: 100,
		description: 'Maximum number of create, update, or delete requests in one node execution',
	},
	{
		displayName: 'Request Timeout (ms)',
		name: 'requestTimeout',
		type: 'number',
		typeOptions: { minValue: 1000, maxValue: 300000 },
		default: 30000,
		description: 'Maximum time for each HTTP request',
	},
	{
		displayName: 'Allow AI Tool Use',
		name: 'allowAiTool',
		type: 'boolean',
		default: false,
		description: 'Whether this credential may be selected by the generated AI Tool variant',
	},
	{
		displayName: 'Allow AI Metadata Discovery',
		name: 'allowAiMetadata',
		type: 'boolean',
		default: false,
		description: 'Whether the AI Tool may inspect metadata for an explicitly allowed service',
		displayOptions: { show: { allowAiTool: [true] } },
	},
	{
		displayName: 'Allow AI Write Operations',
		name: 'allowAiWrites',
		type: 'boolean',
		default: false,
		description:
			'Whether an AI Tool may execute policy-approved Create, Update, or Delete operations',
		displayOptions: { show: { allowAiTool: [true] } },
	},
	{
		displayName: 'AI Tool Maximum Rows',
		name: 'aiToolMaxRows',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 1000 },
		default: 100,
		description: 'Additional row cap applied to AI Tool executions',
		displayOptions: { show: { allowAiTool: [true] } },
	},
	{
		displayName: 'AI Tool Maximum Result Size (Bytes)',
		name: 'aiToolMaxBytes',
		type: 'number',
		typeOptions: { minValue: 1024, maxValue: 5242880 },
		default: 262144,
		description: 'Additional serialized-output cap applied to AI Tool executions',
		displayOptions: { show: { allowAiTool: [true] } },
	},
	{
		displayName: 'AI Tool Maximum Writes Per Execution',
		name: 'aiToolMaxWrites',
		type: 'number',
		typeOptions: { minValue: 1, maxValue: 100 },
		default: 1,
		description: 'Additional write-count cap applied to AI Tool executions',
		displayOptions: { show: { allowAiTool: [true], allowAiWrites: [true] } },
	},
];
